name: Minecraft Server Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  server-test:
    name: Test on Minecraft Server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        minecraft-version: ['1.19.4', '1.20.4']
        server-type: ['paper']
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build Plugin
        run: mvn package

      - name: Set up test server environment
        run: |
          mkdir -p .github/test-server/plugins
          cp target/TDRPlaytime-*.jar .github/test-server/plugins/

      - name: Build and run test container
        working-directory: .github/test-server
        run: |
          # Get latest Paper build for the current Minecraft version
          if [ "${{ matrix.minecraft-version }}" = "1.19.4" ]; then
            PAPER_BUILD=550
          elif [ "${{ matrix.minecraft-version }}" = "1.20.4" ]; then
            PAPER_BUILD=395
          else
            echo "Unsupported Minecraft version"
            exit 1
          fi
          
          # Update Dockerfile environment variables
          sed -i "s/MINECRAFT_VERSION=.*/MINECRAFT_VERSION=${{ matrix.minecraft-version }}/" Dockerfile.test
          sed -i "s/PAPER_BUILD=.*/PAPER_BUILD=$PAPER_BUILD/" Dockerfile.test
          
          # Build and run the container
          docker build -t playtime-test -f Dockerfile.test .
          docker run --name playtime-test-container playtime-test
          
          # Copy logs from container
          docker cp playtime-test-container:/data/logs ./logs
          
          # Check if test was successful
          if [ $? -ne 0 ]; then
            echo "Server test failed"
            exit 1
          fi

      - name: Upload server logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-logs-${{ matrix.minecraft-version }}-${{ matrix.server-type }}
          path: .github/test-server/logs/